### ISSUE TITLE
errors on deeplab.py

### ISSUE THREAD

**Issue by MuseCP** [martinkersner/train-DeepLab#35]
I use deeplab to do segmentation.when I use deeplab.py I meet this error:

```
Traceback (most recent call last):
  File "deeplab.py", line 106, in <module>
    main()
  File "deeplab.py", line 24, in main
    net = Segmenter(net_path, model_path, gpu_id)
  File "/home/muses/train-DeepLab/segmenter.py", line 17, in __init__
    caffe.Net.__init__(self, prototxt, model)
Boost.Python.ArgumentError: Python argument types in
    Net.__init__(Segmenter, str, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
    __init__(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > network_file, int phase, int level=0, boost::python::api::object stages=None, boost::python::api::object weights=None)
```

my command is:

`python deeplab.py 0 ./exper/0822/config/PSP101-ele/pspnet101_ele_8s.prototxt ./exper/0822/model/model_iter_10000.caffemodel ./test/pic/87.png`

how to solve this problem?

**Comment by zjz5250** [comment]
i  have the  same  problem. have you solved it?
